version: "3.9" #optional
# definition of service, volumes and networks

# docker volume ls
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/user/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/user/data/wordpress
      type: volume
      o: bind

# docker network ls
networks:
  frontend:
  backend:

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: img_nginx
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - frontend
    ports:
      - "443:443"
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: img_mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - backend
    environment:
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: img_wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - frontend
      - backend
    environment:
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
    restart: unless-stopped

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    image: img_redis
    networks:
      - backend
    restart: unless-stopped

  ftp-server:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp_serv

    image: img_ftp
    volumes:
      - wordpress-volume:/var/www/wordpress
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PWD=${FTP_PWD}
      - FTP_ROOT=${FTP_ROOT}
    ports:
      - "21:21"
    networks:
      - backend
    restart: unless-stopped

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build:
      context: ./requirements/bonus/adminer
    image: img_adminer
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - frontend
      - backend
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
    restart: unless-stopped
